import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import type { ToolContext } from "../context.js";
import { apiToolResult, registerApiTool } from "../server/api-tool.js";

/**
 * Where a Cloudflare Workers app is hosted: Staticbot's own Cloudflare account, or the customer's.
 *
 * <p>Both tools are read-only projections of Staticbot's hosting decision. The account menu, the
 * labels, which accounts are usable, why one is blocked, and what a hostname resolves to are all
 * decided server-side — these tools only hand the agent the values to render and to pass back. The
 * agent's job is to ASK the user which account to use, not to work one out: it cannot see the
 * Cloudflare account's permissions or which zone a hostname belongs to, and a guess produces a
 * deployment that fails at creation.
 *
 * <p>Nothing here writes, moves or takes over anything. The values echoed back into
 * `create_stack` / `create_deployment` are re-validated when those run, so a stale answer can never
 * authorise a write.
 */
export function registerCloudflareHostingTools(
  server: McpServer,
  { apiFetch, toText }: ToolContext,
): void {
  registerApiTool(server,
    "list_cloudflare_hosting_targets",
    "List the Cloudflare accounts this app can be hosted in: Staticbot's managed account (the default) " +
      "plus any Cloudflare account the user has connected. Call this before create_stack or " +
      "create_deployment for a Cloudflare Workers / SSR app whenever the user has a connected Cloudflare " +
      "account and might want the Worker deployed into it rather than hosted by Staticbot.\n\n" +
      "Read the response, do not compute from it:\n" +
      "- `managed` is the Staticbot-hosted option. It is always present and always valid.\n" +
      "- `customerOptions` lists the user's own accounts — each with a ready-to-render `label` and the " +
      "`value` you pass back verbatim. **Pass `value` through unchanged; never construct or edit one.**\n" +
      "- `notices` explains accounts that could not be offered (a revoked credential, a missing Workers " +
      "permission). Show these to the user — they are the reason an account is missing from the list.\n" +
      "- `selectedValue` / `selectedHostname` are the defaults when `stackId` was supplied.\n\n" +
      "**Do not decide for the user.** If `customerOptionsAvailable` is false, do not ask — Staticbot " +
      "hosting is the only choice. If it is true, present the options (including the managed one) and let " +
      "the user pick. Deploying into the user's own account means the Worker, its domain and its " +
      "certificate live in their account, so it is their decision, not an inference from their setup.\n\n" +
      "Before creating anything with a customer choice, call preflight_cloudflare_hosting — it reports " +
      "collisions that would otherwise fail the deployment.",
    {
      stackId: z.string().uuid().optional().describe(
        "Optional stack ID. When supplied, `selectedValue` and `selectedHostname` come back as that " +
          "stack's current hosting choice and hostname, suitable as the default selection.",
      ),
    },
    { readOnlyHint: true, destructiveHint: false, openWorldHint: false },
    async ({ stackId }) => {
      const qs = stackId ? `?stackId=${encodeURIComponent(stackId)}` : "";
      const data = await apiFetch(`/api/v1/cloudflare/hosting-targets${qs}`);
      return apiToolResult(data, toText);
    },
  );

  registerApiTool(server,
    "preflight_cloudflare_hosting",
    "Check that a hosting choice and hostname can actually be deployed, before create_stack or " +
      "create_deployment. Read-only: it never creates, deletes or takes over anything. It answers for the " +
      "managed choice too, so call it the same way whichever option the user picked.\n\n" +
      "**How to use the result:**\n" +
      "- `ok: true` — deployable. Report `connectionLabel`, and `hostname` / `workerName` when present. " +
      "`note` may add useful context (for example that an apex hostname is supported).\n" +
      "- `ok: false` — **do not create anything.** Show the user `blockingMessage` verbatim; it names the " +
      "exact collision and what to fix in Cloudflare. Resolve it with the user, then call this again.\n" +
      "`warnings` are non-blocking (a check that could not be run) — surface them, but they do not stop " +
      "the deployment.\n\n" +
      "For a customer choice, `hostname` must be a domain that already lives in one of that account's " +
      "zones. An autogenerated Staticbot subdomain cannot be used, and an apex such as `example.com` is " +
      "supported. The answer can go stale — permissions and DNS can change — so call it again after any " +
      "change the user makes, and never treat a previous result as permission.",
    {
      choice: z.string().describe(
        "The `value` of the chosen option from list_cloudflare_hosting_targets — either its `managed.value` " +
          "or a `customerOptions[].value`. Pass it through unchanged.",
      ),
      hostname: z.string().describe(
        "The hostname the app will serve, e.g. 'example.com' or 'app.example.com'. Required for a " +
          "customer account (apex is supported); ignored for the managed choice.",
      ),
    },
    { readOnlyHint: true, destructiveHint: false, openWorldHint: false },
    async ({ choice, hostname }) => {
      const data = await apiFetch("/api/v1/cloudflare/hosting-preflight", {
        method: "POST",
        body: JSON.stringify({ choice, hostname }),
      });
      return apiToolResult(data, toText);
    },
  );
}
